### ISSUE TITLE
Cant Add API limit reached

### ISSUE THREAD

**Issue by peel1** [Coding4TG/TG-ToolsFree#1]
Cant add anyone due to following error:

filestack.exceptions.FilestackHTTPError: {"error":"Your app is currently blocked due to reaching a free limit or unpaid invoice. To upgrade your account or pay any outstanding invoices, login to your Filestack account here: https://dev.filestack.com/login/","timestamp":1725457235}

**Comment by Coding4TG** [comment]
Fixed mate, start the tool again and it will update automatically. After that, the tool is ready to be used.
